from labyrinth_test_case import LabyrinthTestCase
from lwotai import Labyrinth


class WarOfIdeasHandlerTest(LabyrinthTestCase):
    """Test War of Ideas Handler"""

    def test_fail_rolls(self):
        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(1, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(2, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(3, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(4, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(5, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_good())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Gulf States"].is_fair())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)
        app.handleMuslimWoI(6, "Gulf States")
        self.assertTrue(app.map["Gulf States"].is_good())
        self.assertTrue(app.map["Gulf States"].is_ally())
        self.assertEqual(app.map["Gulf States"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(1, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(2, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(3, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(4, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(5, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_ally())
        self.assertEqual(app.map["Pakistan"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_neutral())
        self.assertEqual(app.map["Pakistan"].aid, 0)
        app.handleMuslimWoI(6, "Pakistan")
        self.assertTrue(app.map["Pakistan"].is_fair())
        self.assertTrue(app.map["Pakistan"].is_ally())
        self.assertEqual(app.map["Pakistan"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(1, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(2, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(3, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(4, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 1)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(5, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_fair())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)

        app = Labyrinth(1, 1, self.set_up_test_scenario)
        self.assertTrue(app.map["Saudi Arabia"].is_poor())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)
        app.handleMuslimWoI(6, "Saudi Arabia")
        self.assertTrue(app.map["Saudi Arabia"].is_fair())
        self.assertTrue(app.map["Saudi Arabia"].is_ally())
        self.assertEqual(app.map["Saudi Arabia"].aid, 0)